// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mdres_core_cpp
Rcpp::NumericVector mdres_core_cpp(const arma::mat& Y, const Rcpp::List& Y_pred_list);
RcppExport SEXP _MMLN_mdres_core_cpp(SEXP YSEXP, SEXP Y_pred_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Y_pred_list(Y_pred_listSEXP);
    rcpp_result_gen = Rcpp::wrap(mdres_core_cpp(Y, Y_pred_list));
    return rcpp_result_gen;
END_RCPP
}
// mh_update_normbeta_cpp
Rcpp::List mh_update_normbeta_cpp(const arma::mat& W, const arma::mat& Y, const arma::mat& Mu, const arma::mat& Sigma);
RcppExport SEXP _MMLN_mh_update_normbeta_cpp(SEXP WSEXP, SEXP YSEXP, SEXP MuSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mh_update_normbeta_cpp(W, Y, Mu, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// mh_update_beta_cpp
Rcpp::List mh_update_beta_cpp(const arma::mat& W, const arma::mat& Y, const arma::mat& Mu, const arma::mat& Sigma);
RcppExport SEXP _MMLN_mh_update_beta_cpp(SEXP WSEXP, SEXP YSEXP, SEXP MuSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Mu(MuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mh_update_beta_cpp(W, Y, Mu, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// verify_installation
void verify_installation();
RcppExport SEXP _MMLN_verify_installation() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    verify_installation();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MMLN_mdres_core_cpp", (DL_FUNC) &_MMLN_mdres_core_cpp, 2},
    {"_MMLN_mh_update_normbeta_cpp", (DL_FUNC) &_MMLN_mh_update_normbeta_cpp, 4},
    {"_MMLN_mh_update_beta_cpp", (DL_FUNC) &_MMLN_mh_update_beta_cpp, 4},
    {"_MMLN_verify_installation", (DL_FUNC) &_MMLN_verify_installation, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_MMLN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
