# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mdres_core_cpp <- function(Y, Y_pred_list) {
    .Call(`_MMLN_mdres_core_cpp`, Y, Y_pred_list)
}

mh_update_normbeta_cpp <- function(W, Y, Mu, Sigma) {
    .Call(`_MMLN_mh_update_normbeta_cpp`, W, Y, Mu, Sigma)
}

mh_update_beta_cpp <- function(W, Y, Mu, Sigma) {
    .Call(`_MMLN_mh_update_beta_cpp`, W, Y, Mu, Sigma)
}

verify_installation <- function() {
    invisible(.Call(`_MMLN_verify_installation`))
}

